name: Test & Publish Image

on:
  push:

jobs:
  test_and_publish_image:
    runs-on: ubuntu-latest
    services:
      rabbitmq-streaming:
        image: pivotalrabbitmq/rabbitmq-stream
        env:
          RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: "-rabbitmq_stream"
        ports:
          - 5551:5551
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - uses: actions/checkout@v2

      - name: Test
        run: make test

      - name: Upload coverage to Codecov
        run: bash <(curl -s https://codecov.io/bash)

     - name: Set up Docker Buildx
       uses: docker/setup-buildx-action@v1

     - name: Login to DockerHub
       uses: docker/login-action@v1
       with:
         username: ${{ secrets.DOCKERHUB_USERNAME }}
         password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Publish
        run: |
          VERSION=latest
          export VERSION
          echo "GITHUB_REF:$GITHUB_REF"
          if [[ ! $GITHUB_REF =~ "/tags/" ]]
          then
            VERSION=dev
          fi
          echo $VERSION
          make perf-test-docker-push
